### ISSUE TITLE
Failed to open the WinDivert device (2) (Run on NT AUTHORITY\SYSTEM )

### ISSUE THREAD

**Issue by FunnyWolf** [praetorian-inc/PortBender#1]
![image](https://user-images.githubusercontent.com/17685281/124407255-0550e880-dd76-11eb-9f4e-e862aec0c956.png)

**Comment by FunnyWolf** [comment]
#define ERROR_FILE_NOT_FOUND             2L

**Comment by FunnyWolf** [comment]
after I upload dll and sys to target, all works fine.

**Comment by muxueo** [comment]
您能收到net connection的消息吗
